### ISSUE TITLE
text not centered

### ISSUE THREAD

**Issue by Kikobeats** [piecioshka/react-bounty#1]
I noted the tex is not centered

![screenshot 2019-02-07 at 12 53 28](https://user-images.githubusercontent.com/2096101/52410188-e92ebb80-2ad7-11e9-8322-850a4f7c3cdc.png)

If I tweak the svg, I centered it properly

![screenshot 2019-02-07 at 12 56 09](https://user-images.githubusercontent.com/2096101/52410195-efbd3300-2ad7-11e9-83d4-a8d8ff43e491.png)

![screenshot 2019-02-07 at 12 56 58](https://user-images.githubusercontent.com/2096101/52410202-f186f680-2ad7-11e9-956b-7b8d23464305.png)

The problem is, the svg is loaded from `bounty` so I don't know how I can implement this ¯\_(ツ)_/¯

**Comment by piecioshka** [comment]
As you said — problem exist in `bounty` lib.
This lib is only ported `bounty` to React components world.

@Kikobeats Maybe you can report an issue there?

**Comment by piecioshka** [comment]
@Kikobeats on `bounty` docs https://www.npmjs.com/package/bounty You can found option: `lineHeight: 1.35,`. Try to modify that value.
